name: BookWorm Clean Up
run-name: Delete untagged package versions

# DISABLED: Questa operazione al momento l'ho disabilitata perchè impatta con questo errore
# Restrictions in the Github API prevent us from listing packages when using a $GITHUB_TOKEN token. Because of this, filtering with '!' and '*' are not supported for this token type. Image name bookworm/* is therefore not valid.
# La riabiliteremo quando ci serve veramente, al momento è velleitaria
on:
  workflow_dispatch: # Manual trigger only
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  delete-package-versions:
    name: Delete untagged package versions
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "bookworm/*"
          tag-selection: untagged
          cut-off: 1h