name: BookWorm Clean Up
run-name: Delete untagged package versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-package-versions:
    name: Delete untagged package versions
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: |
            bookworm/apphost
            bookworm/basket
            bookworm/catalog
            bookworm/chat
            bookworm/finance
            bookworm/notification
            bookworm/ordering
            bookworm/rating
            bookworm/scheduler
          tag-selection: untagged
          cut-off: 1h
